FROM tiangolo/uwsgi-nginx-flask:python2.7-alpine3.7

RUN apk add --no-cache --virtual .build-deps \
		gcc \
		musl-dev \
		linux-headers \
	&& pip install --no-cache-dir \
		flask-paginate \
		requests \
		netifaces \
	&& apk del .build-deps

COPY uwsgi.ini /etc/uwsgi/uwsgi.ini
COPY ./uwsgi-streaming.conf /etc/nginx/conf.d/
COPY ./app /app
